<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MenusSeeder extends Seeder
{
    public function run()
    {
        DB::table('menus')->insert([
            [
                'id' => 1,
                'name_text' => 'Dashboard',
                'url_name' => 'dashboard',
                'can_permission' => 'dashboard',
                'icon' => 'fa fa-tachometer',
                'type' => 1,
                'description' => null,
                'order' => 1,
                'parent_id' => null,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 02:44:18'),
                'updated_at' => Carbon::parse('2025-10-20 02:44:18'),
            ],
            [
                'id' => 2,
                'name_text' => 'Setting',
                'url_name' => '#',
                'can_permission' => '#',
                'icon' => 'fa fa-cogs',
                'type' => 1,
                'description' => null,
                'order' => 2,
                'parent_id' => null,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 02:46:12'),
                'updated_at' => Carbon::parse('2025-10-20 02:46:12'),
            ],
            [
                'id' => 3,
                'name_text' => 'Menu',
                'url_name' => 'menu-setting',
                'can_permission' => 'menu-setting',
                'icon' => 'fa fa-bars',
                'type' => 2,
                'description' => null,
                'order' => 3,
                'parent_id' => 2,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 02:53:45'),
                'updated_at' => Carbon::parse('2025-10-20 02:53:45'),
            ],
            [
                'id' => 4,
                'name_text' => 'Users',
                'url_name' => 'user-manage',
                'can_permission' => 'user-manage',
                'icon' => 'fa fa-users',
                'type' => 2,
                'description' => null,
                'order' => 4,
                'parent_id' => 2,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 02:56:19'),
                'updated_at' => Carbon::parse('2025-10-20 02:56:19'),
            ],
            [
                'id' => 5,
                'name_text' => 'Permission',
                'url_name' => 'role-permission',
                'can_permission' => 'role-permission',
                'icon' => 'fa fa-address-card',
                'type' => 2,
                'description' => null,
                'order' => 5,
                'parent_id' => 2,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 03:09:06'),
                'updated_at' => Carbon::parse('2025-10-20 03:09:06'),
            ],
            [
                'id' => 6,
                'name_text' => 'Office',
                'url_name' => 'office-setting',
                'can_permission' => 'office-setting',
                'icon' => 'fa fa-building',
                'type' => 2,
                'description' => null,
                'order' => 6,
                'parent_id' => 2,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 03:11:20'),
                'updated_at' => Carbon::parse('2025-10-20 03:11:20'),
            ],
            [
                'id' => 7,
                'name_text' => 'Department',
                'url_name' => 'department-setting',
                'can_permission' => 'department-setting',
                'icon' => 'fa fa-building',
                'type' => 2,
                'description' => null,
                'order' => 7,
                'parent_id' => 2,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 03:16:38'),
                'updated_at' => Carbon::parse('2025-10-20 03:16:38'),
            ],
            [
                'id' => 8,
                'name_text' => 'Partner List',
                'url_name' => 'partner-management',
                'can_permission' => 'partner-management',
                'icon' => 'fa fa-users',
                'type' => 1,
                'description' => null,
                'order' => 8,
                'parent_id' => null,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 03:45:19'),
                'updated_at' => Carbon::parse('2025-10-20 03:45:19'),
            ],
            [
                'id' => 9,
                'name_text' => 'API White List',
                'url_name' => 'api-whitelist',
                'can_permission' => 'api-whitelist',
                'icon' => 'fa fa-signal',
                'type' => 2,
                'description' => null,
                'order' => 9,
                'parent_id' => 2,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 04:02:10'),
                'updated_at' => Carbon::parse('2025-10-20 04:02:10'),
            ],
            [
                'id' => 10,
                'name_text' => 'Approval',
                'url_name' => 'approval-setting',
                'can_permission' => 'approval-setting',
                'icon' => 'fa fa-file',
                'type' => 2,
                'description' => null,
                'order' => 10,
                'parent_id' => 2,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-10-20 04:14:12'),
                'updated_at' => Carbon::parse('2025-10-20 04:14:12'),
            ],
            [
                'id' => 11,
                'name_text' => 'Generate Form',
                'url_name' => 'admin/form-links',
                'can_permission' => 'admin/form-links',
                'icon' => 'fas fa-file',
                'type' => 1,
                'description' => null,
                'order' => 11,
                'parent_id' => null,
                'is_active' => 1,
                'created_at' => Carbon::parse('2025-11-11 14:20:14'),
                'updated_at' => Carbon::parse('2025-11-11 14:20:14'),
            ],
            [
                'id' => 12,
                'name_text' => 'Export Import',
                'url_name' => '#',
                'can_permission' => '#',
                'icon' => 'fas fa-file',
                'type' => 1,
                'description' => null,
                'order' => 12,
                'parent_id' => null,
                'is_active' => 1,
                'created_at' => Carbon::parse('2026-01-14 10:49:36'),
                'updated_at' => Carbon::parse('2026-01-14 10:49:36'),
            ],
            [
                'id' => 13,
                'name_text' => 'Export Data',
                'url_name' => 'admin/company/export/',
                'can_permission' => 'admin/company/export/',
                'icon' => 'fas fa-list',
                'type' => 2,
                'description' => null,
                'order' => 13,
                'parent_id' => 12,
                'is_active' => 1,
                'created_at' => Carbon::parse('2026-01-14 11:08:31'),
                'updated_at' => Carbon::parse('2026-01-14 11:08:31'),
            ],
            [
                'id' => 14,
                'name_text' => 'Import Data',
                'url_name' => 'admin/company/import/',
                'can_permission' => 'admin/company/import/',
                'icon' => 'fas fa-list',
                'type' => 2,
                'description' => null,
                'order' => 14,
                'parent_id' => 12,
                'is_active' => 1,
                'created_at' => Carbon::parse('2026-01-14 11:10:41'),
                'updated_at' => Carbon::parse('2026-01-14 11:10:41'),
            ],
        ]);
    }
}